97-rubysteps/lessons/007_rails_decoding_business_logic/rubysteps_progress/config/routes.rb
Rails.application.routes.draw do
  resource :learning_session
end

97-rubysteps/lessons/007_rails_decoding_business_logic/rubysteps_progress/app/models/learning_session.rb
class LearningSession
  state_machine :state, initial: :unstarted do
    event :start do
      transition unstarted: :started
    end

    event :choose_lesson do
      transition started: :choosing_lesson
    end

    event :record_questions do
      transition choosing_lesson: :recording_questions
    end

    event :record_notes do
      transition recording_questions: :recording_notes
    end

    event :mark_questions_as_answered do
      transition recording_notes: :marking_questions_as_answered
    end

    event :finish_session do
      transition marking_questions_as_answered: :finished
    end
  end
end

97-rubysteps/lessons/007_rails_decoding_business_logic/rubysteps_progress/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

97-rubysteps/lessons/007_rails_decoding_business_logic/rubysteps_progress/app/controllers/learning_sessions_controller.rb
class LearningSessionsController < ApplicationController
  around_action :restore_and_save_learning_session_state

  def new
  end

  def create
    @learning_session = LearningSession.new # overwrite any restored one
    @learning_session.start

    render action: @learning_session.state
  end

  def update
    if @learning_session.send params[:event]
      render action: @learning_session.state
    else
      render text: "Whoops! Wrong state and event combo"
    end
  end

  def restore_and_save_learning_session_state
    @learning_session = LearningSession.new
    @learning_session.state = session[:learning_session_state] if session[:learning_session_state]

    yield

    session[:learning_session_state] = @learning_session.state
  end
end

97-rubysteps/lessons/007_rails_decoding_business_logic/rubysteps_progress/app/helpers/application_helper.rb
module ApplicationHelper
end

97-rubysteps/lessons/007_rails_decoding_business_logic/rubysteps_progress/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubystepsProgress</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

97-rubysteps/lessons/007_rails_decoding_business_logic/rubysteps_progress/app/views/learning_sessions/choosing_lesson.html.erb
<%= form_tag learning_session_path, method: :put do %>
  <%= label_tag :lesson_number, 'What is the lesson number?' %>
  <%= text_field_tag :lesson_number %>
  <br/>
  <%= hidden_field_tag :event, :record_questions %>
  <%= submit_tag 'Choose lesson' %>
<% end %>

97-rubysteps/lessons/007_rails_decoding_business_logic/rubysteps_progress/app/views/learning_sessions/finished.html.erb
<h1>Woohoo! You have completed another RubySteps learning session</h1>

97-rubysteps/lessons/007_rails_decoding_business_logic/rubysteps_progress/app/views/learning_sessions/marking_questions_as_answered.html.erb
<%= form_tag learning_session_path, method: :put do %>
  <%= label_tag :question_answered, 'Was your question answered?' %>
  <%= radio_button_tag :question_answered, 'Yes' %> Yes
  <%= radio_button_tag :question_answered, 'No' %> No
  <br/>
  <%= hidden_field_tag :event, :finish_session %>
  <%= submit_tag 'Mark questions as answered' %>
<% end %>

97-rubysteps/lessons/007_rails_decoding_business_logic/rubysteps_progress/app/views/learning_sessions/new.html.erb
<%= form_tag learning_session_path, method: :post do %>
  <%= button_tag 'Start a new learning session', type: :submit %>
<% end %>

97-rubysteps/lessons/007_rails_decoding_business_logic/rubysteps_progress/app/views/learning_sessions/recording_notes.html.erb
<%= form_tag learning_session_path, method: :put do %>
  <%= label_tag :note, 'Record a note related to the question' %>
  <%= text_field_tag :note %>
  <br/>
  <%= hidden_field_tag :event, :mark_questions_as_answered %>
  <%= submit_tag 'Record note' %>
<% end %>

97-rubysteps/lessons/007_rails_decoding_business_logic/rubysteps_progress/app/views/learning_sessions/recording_questions.html.erb
<%= form_tag learning_session_path, method: :put do %>
  <%= label_tag :question, 'What is your question for this session?' %>
  <%= text_field_tag :question %>
  <br/>
  <%= hidden_field_tag :event, :record_notes %>
  <%= submit_tag 'Record question' %>
<% end %>

97-rubysteps/lessons/007_rails_decoding_business_logic/rubysteps_progress/app/views/learning_sessions/started.html.erb
<h1>Your learning session has started</h1>

<%= link_to "Click here to continue", {event: :choose_lesson}, method: :put %>